name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build & Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meu-app-angular:latest

      # 5️⃣ Instalar cloudflared no runner
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
            -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared
          cloudflared --version

      # 6️⃣ Abrir túnel SSH local via Cloudflare Access
      - name: Open Cloudflare SSH tunnel
        run: |
          cloudflared access ssh \
            --hostname ssh.vitorperez.dev.br \
            --url localhost:2222 &
          sleep 5

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh

          cat << 'EOF' > ~/.ssh/id_ed25519
      ${{ secrets.SSH_PRIVATE_KEY }}
      EOF

          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2222 localhost >> ~/.ssh/known_hosts


      # 7️⃣ Deploy via SSH LOCAL
      - name: Deploy to VPS
        run: |
          ssh -p 2222 root@localhost << 'EOF'
              cd /caminho/do/seu/compose
              docker compose pull
              docker compose up -d
          EOF
